version: '3.8'

services:
  webapp:
    build:
      context: .
    image: ${APP_NAME:-chatapp}:v${APP_VERSION:-latest}
    container_name: ${APP_NAME:-chatapp}
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge
