version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: my-jenkins
    ports:
      - "8080:8080"   # Web UI
      - "50000:50000" # Agent/Slave connections
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home:
