version: '3.8'

services:
  react-app:
    build:
      context: ./frontend   # Adjust path to your React app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "start"]

  selenium-tests:
    build:
      context: .
    depends_on:
      - react-app
    environment:
      - SELENIUM_URL=http://react-app:3000
