version: '3.8'

services:
  backend:
    image: backend:v1
    container_name: COS_container
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cos_db
      - DEBUG=False
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - cos-network

  frontend:
    image: react-frontend:v1
    container_name: cos_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cos-network

  db:
    image: postgres:13
    container_name: cos_database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cos-network

networks:
  cos-network:
    driver: bridge

volumes:
  postgres_data: